"use client"

import Header from "@/components/Header";
import MoviesDisplay from "@/components/MoviesDisplay";

export default function Home() {

// sessionStorage.setItem("movies", JSON.stringify([
//   {
//     id: "1",
//     title: "Interstellar",
//     poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
//     description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
//     genre: ["Sci-Fi", "Adventure"],
//     duration: 169,
//     rating: 8.7,
//     language: "English",
//   },
//   {
//     id: "2",
//     title: "The Dark Knight",
//     poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
//     description: "Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos.",
//     genre: ["Action", "Crime", "Drama"],
//     duration: 152,
//     rating: 9.0,
//     language: "English",
//   },
//   {
//     id: "3",
//     title: "Inception",
//     poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
//     description: "A thief who steals corporate secrets through dream-sharing technology is given an impossible task.",
//     genre: ["Sci-Fi", "Thriller"],
//     duration: 148,
//     rating: 8.8,
//     language: "English",
//   },
//   {
//     id: "4",
//     title: "Joker",
//     poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
//     description: "A failed comedian begins a descent into madness and chaos in Gotham City.",
//     genre: ["Crime", "Drama", "Thriller"],
//     duration: 122,
//     rating: 8.4,
//     language: "English",
//   },
//   {
//     id: "5",
//     title: "KGF Chapter 2",
//     poster: "https://upload.wikimedia.org/wikipedia/en/d/d0/K.G.F_Chapter_2.jpg",
//     description: "Rocky continues his rise in the underworld while facing powerful enemies.",
//     genre: ["Action", "Drama"],
//     duration: 168,
//     rating: 8.3,
//     language: "Kannada",
//   },
//   {
//     id: "6",
//     title: "Avatar",
//     poster: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
//     description: "A marine on an alien planet becomes torn between following orders and protecting the world he grows to love.",
//     genre: ["Sci-Fi", "Fantasy"],
//     duration: 162,
//     rating: 7.9,
//     language: "English",
//   },
//   {
//     id: "7",
//     title: "Avengers: Endgame",
//     poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
//     description: "The Avengers assemble once more to reverse Thanos' actions and restore balance.",
//     genre: ["Action", "Adventure", "Sci-Fi"],
//     duration: 181,
//     rating: 8.4,
//     language: "English",
//   },
//   {
//     id: "8",
//     title: "Spider-Man: No Way Home",
//     poster: "https://image.tmdb.org/t/p/w500/5weKu49pzJCt06OPpjvT80efnQj.jpg",
//     description: "Peter Parker's identity is revealed, bringing multiverse chaos.",
//     genre: ["Action", "Adventure"],
//     duration: 148,
//     rating: 8.2,
//     language: "English",
//   },
//   {
//     id: "10",
//     title: "Black Panther",
//     poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
//     description: "T'Challa returns home to Wakanda to take his place as king.",
//     genre: ["Action", "Adventure"],
//     duration: 134,
//     rating: 7.3,
//     language: "English",
//   },
//   {
//     id: "11",
//     title: "Titanic",
//     poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
//     description: "A love story unfolds aboard the ill-fated RMS Titanic.",
//     genre: ["Romance", "Drama"],
//     duration: 195,
//     rating: 7.9,
//     language: "English",
//   },
//   {
//     id: "12",
//     title: "The Matrix",
//     poster: "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
//     description: "A hacker discovers the shocking truth about reality.",
//     genre: ["Sci-Fi", "Action"],
//     duration: 136,
//     rating: 8.7,
//     language: "English",
//   },
//   {
//     id: "13",
//     title: "Gladiator",
//     poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
//     description: "A betrayed Roman general seeks revenge in the arena.",
//     genre: ["Action", "Drama"],
//     duration: 155,
//     rating: 8.5,
//     language: "English",
//   },
//   {
//     id: "14",
//     title: "The Lion King",
//     poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
//     description: "A young lion prince flees his kingdom only to learn the meaning of responsibility.",
//     genre: ["Animation", "Drama"],
//     duration: 88,
//     rating: 8.5,
//     language: "English",
//   },
//   {
//     id: "15",
//     title: "Forrest Gump",
//     poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
//     description: "The life story of a simple man with a big heart.",
//     genre: ["Drama", "Romance"],
//     duration: 142,
//     rating: 8.8,
//     language: "English",
//   },
//   {
//     id: "17",
//     title: "Dangal",
//     poster: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
//     description: "A father trains his daughters to become world-class wrestlers.",
//     genre: ["Drama", "Sport"],
//     duration: 161,
//     rating: 8.4,
//     language: "Hindi",
//   },
//   {
//     id: "18",
//     title: "3 Idiots",
//     poster: "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg",
//     description: "Three engineering students explore friendship and life pressures.",
//     genre: ["Comedy", "Drama"],
//     duration: 170,
//     rating: 8.4,
//     language: "Hindi",
//   },
//   {
//     id: "19",
//     title: "Baahubali 2",
//     poster: "https://upload.wikimedia.org/wikipedia/en/d/d0/Baahubali_2_The_Conclusion.jpg",
//     description: "A kingdom’s legacy unfolds with betrayal and war.",
//     genre: ["Action", "Drama"],
//     duration: 171,
//     rating: 8.2,
//     language: "Telugu",
//   },
//   {
//     id: "20",
//     title: "RRR",
//     poster: "https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg",
//     description: "Two revolutionaries fight against the British empire.",
//     genre: ["Action", "Drama"],
//     duration: 187,
//     rating: 8.0,
//     language: "Telugu",
//   }
// ]));


  return (
    <>
      <Header />
      <MoviesDisplay />
    </>
  );
}
